apiVersion: 1

datasources:
  # ─── Prometheus ─────────────────────────────────────────────────────────────
  - name: Prometheus
    uid: afb9wvei1xr0gc        # UID esperado pelo dashboard
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: efe2ycp27uk1sb   # correlaciona com Tempo
    editable: true

  # ─── Tempo ──────────────────────────────────────────────────────────────────
  - name: Tempo
    uid: efe2ycp27uk1sb         # UID esperado pelo dashboard
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: dfbvb6565el8ge    # correlaciona com Loki
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
        tags:
          - key: service.name
            value: service_name
      serviceMap:
        datasourceUid: afb9wvei1xr0gc   # metrics via Prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false
    editable: true

  # ─── Loki ───────────────────────────────────────────────────────────────────
  - name: Loki
    uid: dfbvb6565el8ge         # UID esperado pelo dashboard
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: efe2ycp27uk1sb  # correlaciona com Tempo
          matcherRegex: '"traceid":"(\w+)"'
          name: TraceID
          url: "$${__value.raw}"
    editable: true
